# Generated by Django 4.1.3 on 2022-12-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_documentos_miembros_remove_curso_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('sexo', models.CharField(max_length=40)),
                ('fecha_de_captura', models.DateField()),
                ('en_equipo', models.BooleanField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Miembros',
            new_name='Entrenadores',
        ),
        migrations.DeleteModel(
            name='Documentos',
        ),
    ]
