# Generated by Django 4.1.3 on 2022-12-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_pokemon_rename_miembros_entrenadores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenadores',
            name='badge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrenadores',
            name='indicador',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='badge',
            field=models.IntegerField(default=0),
        ),
    ]
